name: Trigger ASOKA BE Deployment

on:
  push:
    branches:
      - main
      - staging

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs a Deploy project
      - name: Deploy Asoka BE Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "[INFO] Triggering Deployment at $(date)"
          curl -k -X GET "https://145.79.15.244:22165/hook?CH0EX0OPLGIM7hdzUp9NqHfDiTYZ00LVeFLU0lXpOhGZ0rWR"
          echo "[SUCCESS] Deployment Triggered"

      - name: Deploy Asoka BE Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "[INFO] Triggering Deployment at $(date)"
          curl -k -X GET "https://145.79.15.244:22165/hook?u76wQzPnLc0zADcQUwW5yYpFXG7sEa8vmgruMCqbQZhmpeJ7"
          echo "[SUCCESS] Deployment Triggered"
